version: '3.3'

services:
    db:
      image: mariadb
      restart: always
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: 'password'
      ports:
        - '3306:3306'
      volumes:
        - my-db:/var/lib/mysql

    adminer:
      image: adminer
      restart: always
      ports:
        - 8091:8080

  # Names our volume
volumes:
    my-db: